general:
  enabled: true
excludeBlocks: [COBBLESTONE, DIRT]
protectionDelay: 900
messages:
  canNotBreak: "You need to play for an hour before you can break blocks placed by other players. Use /rank to check your playtime."
