name: ProtectoMyBlocko # the plugins name as it should appear in the plugin list /pl
version: 1.0 # the plugin's version
author: Deano3663
main: McEssence.ProtectoMyBlocko.Main
api-version: 1.18
commands:
  reload:
    description: reload ProtectoMyBlocko
    usage: /<command>
    permission: ProtectoMyBlocko.admin.reload
permissions:
  ProtectoMyBlocko.player.*:
    description: Gives access to all ProtectoMyBlocko permissions
    children:
      ProtectoMyBlocko.bypass: true
  ProtectoMyBlocko.admin.*:
    description: Gives access to all ProtectoMyBlocko admin permissions
    children:
      ProtectoMyBlocko.admin.reload: true
  ProtectoMyBlocko.bypass:
    description: Allows you to break other players protected blocks
    default: op
  ProtectoMyBlocko.admin.reload:
    description: Allows you to reload ProtectoMyBlocko configs
    default: op
